### ISSUE TITLE
firebaseについて

### ISSUE THREAD

**Issue by fummicc1** [fummicc1/TechPod-3#10]
firebaseを使うのに必要な知識が乗ってあるサイトあれば教えてください。または、どんな風に検索すればいいか教えてください。

**Comment by fummicc1** [comment]
@ka0ru19

**Comment by fummicc1** [comment]
@ka0ru19
firebaseのプロジェクト名って何でもいいんですか？

**Comment by ka0ru19** [comment]
> firebaseを使うのに必要な知識が乗ってあるサイトあれば教えてください。または、どんな風に検索すればいいか教えてください。

http://qiita.com/ShinokiRyosei/items/f71c73ab8b0de145c5bc

しのきんの記事

**Comment by ka0ru19** [comment]
@fummicc1 プロジェクト名はなんでもいいよー
bundle id はxcodeに合わせてね！

**Comment by fummicc1** [comment]
@ka0ru19 その記事見てやって見ます。返信ありがとうございます！

**Comment by ka0ru19** [comment]
@fummicc1 がんばろう！！ 8/2までキャンプで夜しか返信できないと思う、申し訳ない！！今日みたいに、質問githubに投げてメッセでリマインドしてもらえたら夜には必ず返信する！よろしく

**Comment by fummicc1** [comment]
@ka0ru19 了解です！

**Comment by fummicc1** [comment]
@ka0ru19 すいません、リマインドってURLコピペしてメッセに貼ればいいんですか？

**Comment by fummicc1** [comment]
![2017-07-31 23 40 49](https://user-images.githubusercontent.com/28649401/28782946-bcb464cc-7649-11e7-8db6-a4cf2ab8c9cd.png)
pod file削除時に出たエラー

**Comment by ka0ru19** [comment]
@fummicc1 それで大丈夫！
