### ISSUE TITLE
このアプリのゴールを決めよう

### ISSUE THREAD

**Issue by ka0ru19** [fummicc1/TechPod-3#2]
プロジェクト見たよ！
このアプリのゴールが知りたい！
どんな機能をつけて、どんなUIにするのか、紙に書いて写真撮って、ここに貼ってほしい！

**Comment by ka0ru19** [comment]
**仕様書の例** 
![img_8867](https://cloud.githubusercontent.com/assets/12772045/25998523/5768726a-375c-11e7-95dc-ee0e6ea2bc63.JPG)
こんな感じで！

**Comment by fummicc1** [comment]
音楽に検索機能つけようと思っているんですけど、本当にいいアプリって感じがしないから時間限られてるし、企画書作るなら一から別のアプリ作ってもいいかなみたいな部分があるんですけど、1から別のアプリ作るかこのアプリ改良していくかどっちがいいと思いますか？

**Comment by ka0ru19** [comment]
@fummicc1 アプリ甲子園目指すなら、別のコンセプトでアプリ考えたほうがいいと思った！今作ってるこのアプリを完成させるのにちょってでも抵抗があるなら、新しくふみやの本当に作りたいアプリをすぐにでも作り始めて欲しい！
来週までにこのissueに企画書の写真載せておいて！！
上の写真は例だけど、なるべく詳しく書いて欲しい！俺が見る時間もほしいから **木曜日まで** によろしく！（笑）

**Comment by fummicc1** [comment]
なんかヒントください笑
この前まで、迷子✖️iphone・自信✖️カメラあたり後者は元ネタ的なのががあるんですけどいいかもなって思っててるんんです

**Comment by fummicc1** [comment]
"https://youtu.be/eojP5hNGwP0"

**Comment by fummicc1** [comment]
とりあえず企画書作ってみます

**Comment by ka0ru19** [comment]
@fummicc1 動画のやつおもろいね！でもどうやってアプリに落とし込むかは考えものだね。。
別に正解があるわけじゃないからヒントというヒントもないよ
アドバイスと言うか、考え方としては、身近にあるいろんな問題をアプリで解決できないか考えてみることかな

**Comment by ka0ru19** [comment]
@fummicc1 あといのっちに返信するときは @ka0ru19 って文頭につけてくれるともうちょっと早く返信気付けるかもしれない！よろしく！

**Comment by fummicc1** [comment]
@ka0ru19 
![img_0001](https://cloud.githubusercontent.com/assets/28649401/26032153/fbd1f0c2-38c6-11e7-897f-e07bc63ffbe8.JPG)

**Comment by fummicc1** [comment]
@ka0ru19 ・機能
自分磨きに関するサイトを集めてリーディングリストみたいに簡単に見れる。
(鼻を高くする方法や眼を大きくする方法など)
カメラ機能の搭載
↓
顔の変化をみる(なぜそんなことするかというと顔って25くらいまでは簡単に変わるから。ソースは精神科医)


Snowの人気がある理由
↓
盛れるから
↓つまり
自分の顔に不満がない。自信がつく

醜形恐怖症の可能性
↓
何か別の方法で自分の顔を評価してみてほしい。考え中
ただ面白いことに自分の顔って他人が思っているより悪く評価していることの方が多い
さっきの動画とかみてもそれは明らかなはず






具体的っていうより箇条書きになったしあんまりまとまってないけど、こんな感じなのを作りたいw

**Comment by fummicc1** [comment]
さっきの動画はいつも鏡とかでみている自分の顔じゃなくて自分の顔を違う形で見ることで客観的に見れるよねみたいなことだとおもったです
@ka0ru19 @

**Comment by fummicc1** [comment]
まあ、でもよく考えれば顔が変わるって言っても割合としては低いわけだし、それよりは動画みたいに自分の顔を認めるみたいな方がニーズは高いかも
本当に作ってみたいけどあんまりまとまってないしアプリ甲子園で優勝できるか不安だから、いのっちの意見が欲しい笑
@ka0ru19

**Comment by fummicc1** [comment]
読み返したけど、多分うまく伝わってないかもしれないw

**Comment by ka0ru19** [comment]
@fummicc1 
一通り確認した！
企画書の書き方は画面遷移がわかりやすくてとてもいい！それぞれの画面での機能も書いてあるともっと良くなりそう！

アプリ甲子園で勝つためのアプリを作るなら、アプリ甲子園の審査基準をまず確認してほしい。あと過去の入賞作品から傾向を考えるべきだと思う。
[アプリ甲子園2016 大会概要 リンク](https://www.applikoshien.jp/outline/)

アイデアを考えてアプリに落とし込むことを考えた時に上のリンクの、審査基準と照らし合わせて、いけるかどうか考えてみて

**Comment by ka0ru19** [comment]
@fummicc1 今日の紙、ここに挙げといてーーー！

**Comment by fummicc1** [comment]
![img_0033](https://cloud.githubusercontent.com/assets/28649401/26249751/b6f58412-3ce2-11e7-9e5f-cb08cc38062b.JPG)

**Comment by fummicc1** [comment]
@ka0ru19

**Comment by fummicc1** [comment]
@ka0ru19  [http://docs.fabo.io/swift/uikit/013_uitabbarcontroller.html](url)

**Comment by fummicc1** [comment]
@ka0ru19  このサイトだとapp delegateにコード書いてるけどあってる？

**Comment by ka0ru19** [comment]
@fummicc1 これはstoryboard使わない場合ね。使わない場合はあんな感じでアプリが立ち上がった瞬間の読み込みをappdelegateに書く

**Comment by fummicc1** [comment]
時間なくて全然できなかったから今日やってみる

**Comment by ka0ru19** [comment]
@fummicc1 おけ！スクール早めに来てやってもいいよ👍 17時ごろから俺いるから👍

**Comment by fummicc1** [comment]
りょーかい

**Comment by fummicc1** [comment]
@ka0ru19 今からやります

**Comment by fummicc1** [comment]
@ka0ru19  いまcommitしたけど、viewcontroller4で初期化しないといけないっていうことで怒られてると思うんだけど、画面遷移前のviewcontroller1.swiftのprepareメソッドに渡したいプロパティのコードを書けばいいと思ったんだけど、とったmovieのデータとかタイトル名とかを渡したいから渡す方向が逆な気がしたのと、そもそも、初期化ってcellとかだとinit書いてたけど、viewcontrollerでもcellクラスト同じように描いていいの？

**Comment by fummicc1** [comment]
@ka0ru19 てかイニシャライザあんまり覚えてない

**Comment by ka0ru19** [comment]
@fummicc1 
![image](https://cloud.githubusercontent.com/assets/12772045/26517953/6456cd44-42df-11e7-87da-73fc7a406631.png)
イニシャライザのエラーはvarの宣言で変数に初期値を代入するか、オプショナル型(!か?)で宣言すると直るよ

**Comment by ka0ru19** [comment]
@fummicc1 あと新しくViewController作るときは、語尾に数字つけるんじゃくて、何のViewControllerかわかるように、たとえばHomeViewControllerとか、TimelineViewControllerとか、SettingViewControllerとかにしよう！

**Comment by ka0ru19** [comment]
@fummicc1 でも新しくファイル作ってすぐcommitするのGood!! commitメッセージに、どんな変更をしたのか書けるとさらにいい！ 頑張ろう！

**Comment by fummicc1** [comment]
@ka0ru19 頑張る

**Comment by fummicc1** [comment]
@ka0ru19 このサイト[http://karel.tsuda.ac.jp/lec/swift/SwiftAVFMovie/](url)参考にしてコード書くつもりなんだけどさ、実行時previewのところを常に表示みたいな風にしたいんだけど、なんてコード書いたらいいのか分かんない

**Comment by fummicc1** [comment]
http://karel.tsuda.ac.jp/lec/swift/SwiftAVFMovie/
