### ISSUE TITLE
FirebaseStorageからダウンロードせずにサムネを表示する

### ISSUE THREAD

**Issue by ShinokiRyosei** [fummicc1/TechPod-3#20]
http://qiita.com/k-boy/items/3d6aa6c26a0c6510320e

**Comment by fummicc1** [comment]
@ShinokiRyosei 
sd_WebImageを使ってcellのサムネイルだけでなく、userのアイコンをダウンロードし、自動的にキャッシュしてくれるようにしました。けど、http://blogios.stack3.net/archives/288　,https://stackoverflow.com/questions/39881566/how-to-clear-all-cached-images-loaded-from-sdwebimageを見てると、キャッシュしてくれることによってサムネイルやアイコンのダウンロードを省略してくれるらしいんですけど、
今の問題点としては、サムネイルのキャッシュを削除するのは好ましくないが、以下のSDImageCache.shared().clearMemory()
を行っており、全てのキャッシュを削除している。これ以外の方法として、https://github.com/rs/SDWebImage/blob/master/Docs/HowToUse.md
に書いてある個々にキャッシュを行うみたいな内容があったんですけど、使えると思いますか
![2017-08-29 14 34 26](https://user-images.githubusercontent.com/28649401/29806046-0474c4e8-8cc8-11e7-95f9-f52391650296.png)
![2017-08-29 14 39 28](https://user-images.githubusercontent.com/28649401/29806053-13ba687c-8cc8-11e7-97c3-24550b5e1991.png)

**Comment by fummicc1** [comment]
http://keita-matsushita.hatenablog.com/entry/2017/01/23/143108

**Comment by ShinokiRyosei** [comment]
そもそもなんのためにキャッシュを削除をコードを書いてんの？
