### ISSUE TITLE
CellのAutolayoutについて

### ISSUE THREAD

**Issue by fummicc1** [fummicc1/TechPod-3#3]
実装したいこと：Cellの高さを自動可変にするために、AutoLayoutを設定する

**Comment by ka0ru19** [comment]
@fummicc1 cellの高さの自動可変にAutoLayoutが必要なことによく気づいたね！
オートレイアウトは[このサイト](http://type.jp/et/log/article/ra-ios-tips06)みて、この通りにアプリ作って実際にやってみて！多分30分くらいで終わる
このサイトのautolayoutが終わったらきっとcellでもできると思う！
