### ISSUE TITLE
ローカルに保存した動画が再度起動時に読み込めない問題

### ISSUE THREAD

**Issue by ka0ru19** [fummicc1/TechPod-3#6]

**Comment by ka0ru19** [comment]
http://nakajijapan.github.io/blog/2014/06/01/app-doujou3/

**Comment by ka0ru19** [comment]
そろそろ情報垂れ流しでもったいないから、いったんgithubに記事貯めるね
ローカルにどうが
動画を保存する方法の王道をまず徹底調査する必要がありそう
おれもまだ何が一番メジャーで安全だかわからん

**Comment by fummicc1** [comment]
[http://qiita.com/morimorim/items/301cd85f83523b3bb56e](url)

**Comment by ka0ru19** [comment]
404返ってきたそのサイト URLあってる？

**Comment by fummicc1** [comment]
http://qiita.com/morimorim/items/301cd85f83523b3bb56e

**Comment by ka0ru19** [comment]
見れた！！使えると思う！！

**Comment by ka0ru19** [comment]
@fummicc1

**Comment by ka0ru19** [comment]
>
![image](https://user-images.githubusercontent.com/12772045/28410026-5dff5642-6d77-11e7-8a2e-526b66d86ca2.png)

filepathの名前を確認するだけならflatMapいらないんじゃない？
`print(fileNames)` で出力はされると思うよ
中身まで見たかったら、Dataとしてみても本当に動画かどうかわからないから、実際にパスのどれかひとつを選んで動画として出力してみるってのは？どう？

**Comment by ka0ru19** [comment]
>
![image](https://user-images.githubusercontent.com/12772045/28410655-43517d64-6d79-11e7-8c29-cb618f521cee.png)

そしたらその中のうちの１つのパスを、パスの前にDocumentパスつけて、動画として読み込んでプレビューしてみよう

**Comment by ka0ru19** [comment]
@fummicc1
