### ISSUE TITLE
ImageViewとImageがずれる問題

### ISSUE THREAD

**Issue by fummicc1** [fummicc1/TechPod-3#7]
[http://qiita.com/sintario/items/67e9d73f10f0653df655](url)

**Comment by fummicc1** [comment]
[[LayoutConstraints] Unable to simultaneously satisfy constraints. Probably at least one of the constraints in the following list is one you don't want.](url)

**Comment by ka0ru19** [comment]
@fummicc1 これも404だよ

**Comment by fummicc1** [comment]
[http://qiita.com/kaibadash@github/items/73b401a0aff8e7469dbb](url)

**Comment by fummicc1** [comment]
ダメですね

**Comment by ka0ru19** [comment]
http://qiita.com/sintario/items/67e9d73f10f0653df655

**Comment by ka0ru19** [comment]
![image](https://user-images.githubusercontent.com/12772045/28412663-d73ede62-6d7f-11e7-9544-5662788d657b.png)

オートレイアウトミスってるわけじゃなければそんなに問題ないと思うよ
一応swiftにconvertしたもの載せてみた

**Comment by ka0ru19** [comment]
https://objectivec2swift.com/#/home/main 一応このサイトで書き換えできる

**Comment by ka0ru19** [comment]
@fummicc1 みてみて

**Comment by fummicc1** [comment]
すいません、さっき気づきました
