### ISSUE TITLE
七月中にやること

### ISSUE THREAD

**Issue by fummicc1** [fummicc1/TechPod-3#8]
削除機能多分つけれたので、fairebase使いたいです

**Comment by fummicc1** [comment]
@ka0ru19

**Comment by ka0ru19** [comment]
firebaseね
いいねいいね
ローカルの機能は完璧？？

**Comment by ka0ru19** [comment]
## 今runして思ったこと

### ListTableView
  - cellのサムネイル写真の向きを直す
  - cell のlabelのUIはこれでいいの？
  - 一度cellを選択してから再度tableViewに戻ってきた時に選択したcellがハイライトされたまま問題
  - ふと気がつくと下のTabBarが消えてる

### TakeMovieViewController 
  - 再生、停止ボタンのUIはこれでいいの？
    - いきなり停止ボタン押すと落ちるので、落ちるのを回避する処理を書く
  - 撮影中は撮影中とわかるようなUIにしたいね

### TestPreviewViewController
  - 再生時間を示す何かがほしい
    - 例えばprogressBar
  - 動画の再生が終わったらalertが出て、投稿するか否か選べるようになってるけど、これはボタンとかにしたほうが使いやすいんじゃないかな？

### PostViewController
  - textFieldがキーボードに隠れていて見えない

### その他、全体的にみて
  - 動画は横向きで撮る想定にしたほうがいいんじゃないかな
  - アプリは基本縦表示だけど撮影と再生のときだけ横画面のUIにするとか
  - どの画面でも前の画面に戻れるようにしたいね

## firebaseを導入するにあたって
### クラウド管理するものの決定
  - まず、何をfirebaseに送って、何をローカルで管理するべきか考えること
    - ユーザの情報とか、動画の形式、サイズとか

### ユーザ登録
  - firebaseの醍醐味でもある
  - id, password, 名前や紹介文やアイコン画像などのユーザ情報の定義
  - ユーザの新規登録、変更、削除など

**Comment by ka0ru19** [comment]
@fummicc1 夜遅くにごめんね、ちょっと上に書いたもの確認してみて！

**Comment by fummicc1** [comment]
もう寝るので、明日起きたら確認します。忙しい中ありがとうです！@ka0ru19

**Comment by fummicc1** [comment]
すごい、自分じゃ全然気づかなかった

**Comment by fummicc1** [comment]
# 疑問点・要望
-TakeMovieVCでデヴァイスの向きを検知したつもりだが、上手くいかない
-UIのデコレーションが何がいいのかわからない。見た目を工夫したい
-一応initializeVCに戻ることはできるが、UITransitionViewが複数生成されてしまうためか、重い。解決策として、[http://qiita.com/marty-suzuki/items/b69adbc5ee8d870f662f](url)をみた。できれば、いのっちも煮てみてもしいです。よくわからないので

**Comment by fummicc1** [comment]
Markdown記法上手くいかなかった笑

**Comment by fummicc1** [comment]
"http://qiita.com/marty-suzuki/items/b69adbc5ee8d870f662f"

**Comment by fummicc1** [comment]
上のサイト見てみて欲しいです

**Comment by fummicc1** [comment]
ー食べ物
　　ーリンゴ

**Comment by fummicc1** [comment]
ー　食べ物
　　　ー　リンゴ

**Comment by fummicc1** [comment]
- 食べ物
　　-リンゴ

**Comment by ka0ru19** [comment]
@fummicc1 今runして確認した！！
だいぶ見やすくなったね！！！！

https://teratail.com/questions/67476
戻り方、これとか参考になるかも！

**Comment by ka0ru19** [comment]
追記

## runして思ったこと
### ListTableView
- cellを削除した時、その後に残ってるcellタップすると落ちる問題

**Comment by fummicc1** [comment]
@ka0ru1
とりあえず、NavigationBarつけて見たいんですけど、どうでしょう

**Comment by ka0ru19** [comment]
@fummicc1 どこにnavigationbarつける？ 全部に付ける必要があるわけじゃないから、必要に応じてsegue使い分けてほしい

**Comment by ka0ru19** [comment]
コードで書く前に簡単に企画書的な紙で、それぞれの画面間のsegueをどうするのか、書いて見せてほしい

**Comment by fummicc1** [comment]
@ka0ru19 
わかりました！書いてみます

**Comment by fummicc1** [comment]
![img_3626](https://user-images.githubusercontent.com/28649401/28703732-f09d6f64-73a0-11e7-9391-0f49abc38509.JPG)

**Comment by fummicc1** [comment]
@ka0ru19

**Comment by ka0ru19** [comment]
@fummicc1 
遅くなってごめん！！！！
![28703732-f09d6f64-73a0-11e7-9391-0f49abc38509](https://user-images.githubusercontent.com/12772045/28716669-6ca463fa-73d9-11e7-9716-fe3020af0183.jpg)

**Comment by fummicc1** [comment]
なるほど！
疑問なんですけど、動画を投稿した後dismiss で戻る時の実装方法がはっきりわかってないんですけど、とりあえず後回しにするのでアドバイスお願いします！

**Comment by ka0ru19** [comment]
@fummicc1 赤のコメントのように企画書書き直してみてから実装してみて

---

追記:
### 2個戻りたかったらこのコード
```
self.presentingViewController?.presentingViewController?.dismiss(animated: true, completion: nil)
```
参考: http://qiita.com/omatty198/items/cb037b8aa8b9b410be03

**Comment by fummicc1** [comment]
今やってるんですけど、dismiss で戻った時にcellの更新が行われないんですけど、個人的にview WillAppear などのメソッドに書くと、投稿しなかった時にもその処理が行われて処理の分岐が必要だと思うんですけど、複雑で何か工夫したいんですけど、どうしたらいいか分かりません問題です。
@ka0ru19

**Comment by fummicc1** [comment]
# 解決できない問題点
-    dismissをするとtabbar の表示はクリアできるけど、post した動画が反映されない

**Comment by fummicc1** [comment]
何回も同じ質問してる気がするけどヒントお願いします
Cellforrowat 特有の引数が使えないので、手こずってます

**Comment by fummicc1** [comment]
https://teratail.com/questions/12942
このサイト見るとUINavigationController使った方がいいっぽいです

**Comment by fummicc1** [comment]
![2017-07-29 18 26 46](https://user-images.githubusercontent.com/28649401/28743704-9ef605ea-748b-11e7-964a-030b245eea5f.png)
TakeMovieVCの"録画中"を押すとたまにでるこのバグがわからない…
@ka0ru19

**Comment by ka0ru19** [comment]
@fummicc1 ちょっと今日みる時間無いかも！！！ごめん、明日の18時まで進められるところ進めて、わからないとことバンバン挙げといて :+1: あと、firebaseのユーザ登録とかデータベースにjson形式で何を保存するかとか、考えて書き出してみて！ちなみにfirebase、文字列はデータベース、メディア（動画とか）はStorageってところに保存する。Storageに保存するメディアには名前つけられるから、その名前はデータベースのほうで管理するといいのかも！
いろいろやり方あるからぐぐってみて

**Comment by ka0ru19** [comment]
> TakeMovieVCの"録画中"を押すとたまにでるこのバグがわからない…

![image](https://user-images.githubusercontent.com/12772045/28744237-517fb5a2-7497-11e7-87bf-28e0eb3df2a9.png)

エラーぐぐってら何やら記事が出てきた

**Comment by fummicc1** [comment]
返信ありがとうございます😊
その調べ方してみますね。
Firebase 早めに理解しておきます
@ka0ru19

**Comment by fummicc1** [comment]
# 解決できない問題点
-    dismissをするとpost した動画が反映されるがtabbar の表示はされない
-    NavigationBarを実装して、試して見た。今度はtabbarは表示されるが、cellの更新が行われない

**Comment by fummicc1** [comment]
reloadDataでいけるはずなのに、なんかうまくいきません

**Comment by fummicc1** [comment]
http://qiita.com/YusukeHosonuma/items/95315add4004b59e5f00
ここに出てくる、処理分岐が必要なんですけど、このクロージャーの使い方、よくわからなくて困ってます
@ka0ru19

**Comment by fummicc1** [comment]
結構変わってるかもしれないですけどどうですか？

**Comment by fummicc1** [comment]
@ka0ru19 画面の向き、横向きなら横向きのまま、縦向きなら縦向きのままpreviewを表示させたいんですけど、後回しの方がいいですか？
