### ISSUE TITLE
画面遷移がおかしい問題

### ISSUE THREAD

**Issue by ka0ru19** [fummicc1/TechPod-3#9]
>>>プッシュしたんですけど、なんかおかしいです
dismissするとページがめくれるみたいに戻っていっちゃいます
Chieri Suzukiさんが2017年7月24日 22:36に閲覧
10:31

>>井上航
みてみる
dismissのanimation指定してる？
田中 郁弥
田中 郁弥
animationをfalseにしてやって見たんですけど、あんまり変わりませんでした…
あと、dismiss使うと、前の画面を表示するだけで、cellForRowAtメソッドとかが呼ばれなくて、レルムに保存はされてるんですけど、表示できないみたいです
井上航
https://github.com/fummicc1/TechPod-3/commit/1898cd2a059028ded248b7f3703916a5f3fcb941
dismissでも戻った先のviewControllerのviewDidAppearかviewWillAppearは呼ばれてるから、そこでtableviewをreloadすれば更新されるはず
viewDidAppearもviewWillAppearも
13:52

>田中 郁弥
田中 郁弥
すいません、返信遅れました。
viewWillappearが呼ばれてるのは確認できたんですけど、画面遷移のUIがおかしくて、悩んでるんですけど
NavigationViewControllerを使うのってありだと思いますか？
その、画面遷移の時に階層的に戻れるらしいので
田中 郁弥さんが13:54に閲覧

**Comment by ka0ru19** [comment]
NavigationViewControllerいいと思うけど、いつでもTabBar触って戻る以外で別の画面に行けちゃうのが問題だなあ

**Comment by ka0ru19** [comment]
@fummicc1 動画撮影から投稿までの画面遷移、Modal重ねまくりでもいいと思うよ 最後に投稿したら、全部のModal閉じたらTabbarちゃんと表示されるはずなんだけどな

**Comment by fummicc1** [comment]
animated false
にしても、TestPreviewControllerが一瞬表示されてしまうのが直らなくて今考え中です。
あと、tabbarは全部dismissしていくと、表示されました

**Comment by ka0ru19** [comment]
@fummicc1 一瞬表示ならいいんじゃない？ 結構気になる？

**Comment by fummicc1** [comment]
@ka0ru19 動画見ます？

**Comment by fummicc1** [comment]
ここにのっけていいんですか？

**Comment by fummicc1** [comment]
#　問題点

**Comment by fummicc1** [comment]
NavigationViewController使うと、"http://blog.hikware.com/article/177622706.html"みたいに、NavigationViewControllerにつないでる限りは一つのViewControllerしか表示されないから、軽くなりそう。違うかもしれないけど

**Comment by fummicc1** [comment]
"http://blog.hikware.com/article/177622706.html"

**Comment by ka0ru19** [comment]
>"http://blog.hikware.com/article/177622706.html"

いい記事みつけたね

**Comment by ka0ru19** [comment]
>TimeLineViewController
動画をPostした後、dismissで戻ることでViewDidLoadも呼ばれない。
再描画できない
reloadDataしてもnumberOfRowsInSectionは呼ばれないので、Cellの表示個数とRealmオブジェクトの個数が一致せず、Index Out Of Range

これに関してはviewWillAppearとかに、realmから取得して完了したらtableViewをreloadするコード書いて回避できるはずなんだけど、、

**Comment by ka0ru19** [comment]
@fummicc1 確認してみて

**Comment by fummicc1** [comment]
返信遅れました。具体的にどうコードを書いていいのかわからないので、もう少し詳しく教えてください…すいません。
それと、横向きでとる際に、バグが発生しているので、そのスクショをメッセンジャーで送るのでみて欲しいです。
@ka0ru19

**Comment by fummicc1** [comment]
http://qiita.com/osamu1203/items/9c2154123731b3bf629a

**Comment by ka0ru19** [comment]
UIパーツにrotateかけられなかったっけ

**Comment by ka0ru19** [comment]
横向き許可してデバイスを横にするとUIバグるから、極力横向きにはしたくない

**Comment by ka0ru19** [comment]
今までの動画の撮影同様に、カメラの入力は全画面に表示して、ボタンの文字とかを横からでも読めるようにしてあげたらいいんじゃないかな

**Comment by ka0ru19** [comment]
ちょっと明後日の夜までに時間見つけてコード書いて見るから、できるだけちゃんと動く状態のpushだけしといて欲しい

**Comment by ka0ru19** [comment]
1回ちゃんと動くやつpushして、そのpushだけ覚えておいてくれたらそれ教えてくれたら👌

**Comment by ka0ru19** [comment]
進められるところを進めよう

**Comment by ka0ru19** [comment]
@fummicc1 確認よろしく

**Comment by fummicc1** [comment]
本当にすいません。今気づきました。今からプッシュします！
横画面、今は実装すべきじゃないことに今更気づきました。

**Comment by fummicc1** [comment]
@ka0ru19

**Comment by fummicc1** [comment]
今日結構、横画面対応のAutoLayoutとかのほかに、PostViewControllerからのTimeLineViewControllerへの画面遷移のUIを改善した方がいいと思ってて（カクカクしてて使いづらい）、それで今はViewControllerをsegueでpresentしているから全部のViewが積み重なった状態でdismissした際にどうしても今のような形で画面遷移が行われているので、NavigationViewControllerを使えば、多分表示させるViewを減らせれると思っているんですけど、時間があるときに、この問題についてアドバイスが欲しいです。
@ka0ru19

**Comment by fummicc1** [comment]
後、いのっちなしで今何を進めるべきかわからないです…

**Comment by ka0ru19** [comment]
@fummicc1 どんなときにどのsegueを使うべきか、まず知っておいたほうがいいかもね
https://ja.stackoverflow.com/questions/17290/swift-segue%E3%81%AE%E7%A8%AE%E9%A1%9E%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6

**Comment by fummicc1** [comment]
https://ja.stackoverflow.com/questions/28816/破棄ボタンを押したタイミングで保持していたviewcontrollerを解放したい

**Comment by fummicc1** [comment]
返信ありがとうございます。試して見ます
